query GetMenuTree
{
  menuTree {
    id
    name
    path
    icon
    order
    parentId
    createdAt
    updatedAt
    childMenus {
      id
      name
      path
      icon
      order
      level
      parentId
      createdAt
      updatedAt
      childMenus {
        id
        name
        path
        icon
        order
        level
        parentId
        childMenus {
          id
          name
          path
          level
          icon
          order
          parentId
        }
    }
    }
  }
}
